  name: SimpleTreeCap
  main: com.gmail.jlmerrett.SimpleTreeCap.SimpleTreeCap
  version: 1.3.0
  api-version: 1.18
  author: OffJosh
  commands:
    treecap:
      description: Toggle the TreeCap plugin - will always start disabled.
      usage: /treecap [enable|disable|query]